/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{shape_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Model */
        get: operations["read_model_api_models__shape_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Model */
        post: operations["preview_model_api_models_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BoxPreview */
        BoxPreview: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Color */
            color: string;
            center: components["schemas"]["Vector3"];
            /** Volume */
            volume: number;
            bounding_box: components["schemas"]["Vector3"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            shape_type: "box";
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Depth */
            depth: number;
        };
        /** BoxPreviewRequest */
        BoxPreviewRequest: {
            center: components["schemas"]["Vector3"];
            /** Color */
            color?: string | null;
            /** Label */
            label?: string | null;
            /**
             * Shape Type
             * @default box
             * @constant
             * @enum {string}
             */
            shape_type: "box";
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Depth */
            depth: number;
        };
        /** CylinderPreview */
        CylinderPreview: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Color */
            color: string;
            center: components["schemas"]["Vector3"];
            /** Volume */
            volume: number;
            bounding_box: components["schemas"]["Vector3"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            shape_type: "cylinder";
            /** Radius */
            radius: number;
            /** Height */
            height: number;
        };
        /** CylinderPreviewRequest */
        CylinderPreviewRequest: {
            center: components["schemas"]["Vector3"];
            /** Color */
            color?: string | null;
            /** Label */
            label?: string | null;
            /**
             * Shape Type
             * @default cylinder
             * @constant
             * @enum {string}
             */
            shape_type: "cylinder";
            /** Radius */
            radius: number;
            /** Height */
            height: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             * @enum {string}
             */
            status: "ok";
        };
        /** ModelCatalogResponse */
        ModelCatalogResponse: {
            /** Models */
            models: (components["schemas"]["BoxPreview"] | components["schemas"]["SpherePreview"] | components["schemas"]["CylinderPreview"])[];
        };
        /** SpherePreview */
        SpherePreview: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Color */
            color: string;
            center: components["schemas"]["Vector3"];
            /** Volume */
            volume: number;
            bounding_box: components["schemas"]["Vector3"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            shape_type: "sphere";
            /** Radius */
            radius: number;
        };
        /** SpherePreviewRequest */
        SpherePreviewRequest: {
            center: components["schemas"]["Vector3"];
            /** Color */
            color?: string | null;
            /** Label */
            label?: string | null;
            /**
             * Shape Type
             * @default sphere
             * @constant
             * @enum {string}
             */
            shape_type: "sphere";
            /** Radius */
            radius: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vector3 */
        Vector3: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalogResponse"];
                };
            };
        };
    };
    read_model_api_models__shape_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Primitive model type to preview. */
                shape_type: "box" | "sphere" | "cylinder";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoxPreview"] | components["schemas"]["SpherePreview"] | components["schemas"]["CylinderPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_model_api_models_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoxPreviewRequest"] | components["schemas"]["SpherePreviewRequest"] | components["schemas"]["CylinderPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoxPreview"] | components["schemas"]["SpherePreview"] | components["schemas"]["CylinderPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
